apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL215c3FsOjMzMDYvZmlhcC0wMQ==
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=
